Repository Unibeautify/website, pull requests merged in 2018-09, with the labels that each got.

#154 Add sqlformat
  package.json
  scripts/beautifiers.ts
  scripts/netlify.sh
  website/sidebars.json
Labels: add beautifier

#167 Update ugly-samples dep, fix SQL examples
  package.json
  scripts/generate-docs/OptionsDoc.ts
  website/i18n/en.json
  yarn.lock
Labels: add example

#169 Add contributing examples doc
  .gitignore
  scripts/generate-docs/ContributingExamples.ts
  scripts/generate-docs/LanguageDoc.ts
  scripts/generate-docs/MarkdownBuilder.ts
  scripts/generate-docs/OptionsDoc.ts
  scripts/generate-docs/index.ts
  scripts/generate-docs/utils.ts
  website/i18n/en.json
  website/sidebars.json
  website/siteConfig.js
Labels: enhancement, help wanted

#172 Improve contributing examples doc, add summary
  scripts/generate-docs/ContributingExamples.ts
  scripts/generate-docs/MarkdownBuilder.ts
Labels: enhancement

#174 Check readme updated
  .travis.yml
  README.md
  package.json
Labels: enhancement

#176 Improve contributing examples doc, update beautifiers
  scripts/generate-docs/ContributingExamples.ts
  scripts/generate-docs/OptionsDoc.ts
  scripts/generate-docs/utils.ts
  website/i18n/en.json
  website/pages/en/index.js
  website/sidebars.json
Labels: add example, enhancement, help wanted

#187 Update beautifier-eslint to 0.6.0
  package.json
  yarn.lock
Labels: enhancement

#190 Add TSLint beautifier
  README.md
  package.json
  scripts/beautifiers.ts
  website/i18n/en.json
  website/sidebars.json
  yarn.lock
Labels: add beautifier

#193 Add CSSComb beautifier
  README.md
  package.json
  scripts/beautifiers.ts
  website/i18n/en.json
  website/sidebars.json
  yarn.lock
Labels: add beautifier

#192 Add install link to Unibeautify CI
  docs/getting-started.md
  docs/integration-bitbucket.md
  docs/integration-github.md
  docs/integration-gitlab.md
  website/i18n/en.json
  website/pages/en/index.js
  website/siteConfig.js
Labels: enhancement, help wanted, high priority
